//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendee
    {
        public int AttendeeID { get; set; }
        public string custom { get; set; }
        public string txnID { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public string payerFisrtName { get; set; }
        public string payerLastName { get; set; }
        public string payerEmail { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> paymentGross { get; set; }
        public string paymentStatus { get; set; }
    }
}
